#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Homebrew
#

eval "$(/opt/homebrew/bin/brew shellenv)"

#
# Kubectl
#

# completions for kubectl
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)

# Krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

#
# nvm
#

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

#
# Chrome (Canary)
#

alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
alias chr='/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary'

#
# Git
#

alias gacp='git add -A && git commit && git push'

function gacpm() git add -A && git commit -m "$@" && git push
